all:
  vars:
      ansible_connection: ssh
      ansible_user: root
      ansible_ssh_private_key_file: /home/fred/.ssh/mac-private
      code_server_password: password
  hosts:
    server-0:
      ansible_host: 174.138.31.140
    
  
