- name: Config Code Server
  hosts: all
  tasks: 

  - name: Copy code-server service
    template:
      src: ./template/code-server.service.j2
      dest: /lib/systemd/system/code-server.service

  - name: Start and enable code server service
    systemd:
      daemon_reload: yes
      name: code-server
      enabled: true
      state: started

- name: Config Nginx
  hosts: all
  tasks:   
  # Copy config file needed for nginx
  - name: Copy and config code-server.conf
    template:
      src: ./template/code-server.conf.j2
      dest: /etc/nginx/sites-available/code-server.conf

  # sudo ln -s /etc/nginx/sites-available/code-server.conf /etc/nginx/sites-enabled/code-server.conf 
  - name: Create a symbolic link /etc/nginx/sites-available/code-server.conf /etc/nginx/sites-enabled/code-server.conf 
    file:
      src: /etc/nginx/sites-available/code-server.conf
      dest: /etc/nginx/sites-enabled/code-server.conf
      state: link

  # sudo systemctl restart nginx
  - name: Restart nginx service
    systemd:
      daemon_reload: yes
      name: nginx
      state: restarted